spring:
  cloud:
    nacos:
      server-addr: 116.62.127.19:8848
      # ?????????
      username: 'nacos'
      password: 'nacos'
      discovery:
        server-addr: 116.62.127.19:8848
      config:
        enabled: false
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

  application:
    name: mall-gateway
server:
  port: 88

